debian_version: "12.5.0"
debian_mirror: "ftp.us.debian.org"
netboot_url: "https://ftp.debian.org/debian/dists/stable/main/installer-amd64/current/images/netboot/netboot.tar.gz"
tftp_root: "/srv/tftp"
nfs_root: "/srv/nfs/debian"

# Network interface to bind PXE/DHCP services.
# Automatically detected per machine via ansible_facts.default_ipv4 or active interfaces if not overridden.
pxe_interface: ""

pxe_subnet: "192.168.1.0"
pxe_netmask: "255.255.255.0"
pxe_range_start: "192.168.1.200"
pxe_range_end: "192.168.1.240"
pxe_router: "192.168.1.1"
pxe_dns: "1.1.1.1, 8.8.8.8"
pxe_server_ip: "192.168.1.148"
