- name: Install python3, pip, and venv system packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: yes

- name: Install system dependencies for Python packages
  ansible.builtin.apt:
    name:
      # General build tools
      - build-essential
      - python3-dev
      # For PyAudio (from RealtimeSTT)
      - portaudio19-dev
      # fugashi-plus should handle MeCab, but these are here just in case.
      - mecab
      - libmecab-dev
      - mecab-ipadic-utf8
      # For tokenizers (from transformers)
      - rustc
      - cargo
    state: present
  become: yes

- name: Create pipecatapp application directory
  ansible.builtin.file:
    path: /opt/pipecatapp
    state: directory
    mode: '0755'
  become: yes

- name: Create a virtual environment for the pipecat app
  ansible.builtin.command:
    cmd: python3 -m venv /opt/pipecatapp/venv
    creates: /opt/pipecatapp/venv/bin/pip
  become: yes

- name: Create a persistent temporary directory for pip builds
  ansible.builtin.file:
    path: /var/tmp/ansible_pip_build
    state: directory
    mode: '0777'
  become: yes

- name: Copy requirements.txt to remote host
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/ansible/roles/python_deps/files/requirements.txt" # <-- CORRECTED PATH
    dest: /opt/pipecatapp/requirements.txt
  become: yes

- name: Configure git to use anonymous protocol for GitHub
  ansible.builtin.git_config:
    name: url.https://github.com/.insteadOf
    scope: system
    value: git://github.com/
  become: yes

- name: Install/Upgrade base python packages in venv
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
      - wheel
      - cython
    state: latest
    executable: /opt/pipecatapp/venv/bin/pip3
  become: yes

- name: Install python dependencies with a custom temp directory
  block:
    - name: Install python dependencies into the virtual environment
      ansible.builtin.pip:
        requirements: /opt/pipecatapp/requirements.txt
        executable: /opt/pipecatapp/venv/bin/pip3
  environment:
    TMPDIR: /var/tmp/ansible_pip_build
  become: yes

- name: Clean up pip build directory
  ansible.builtin.file:
    path: /var/tmp/ansible_pip_build
    state: absent
  become: yes

- name: Copy pipecat app
  ansible.builtin.copy:
    src: app.py
    dest: /opt/pipecatapp/app.py
  become: yes

- name: Copy pipecatapp Nomad job file
  ansible.builtin.template:
    src: ../../jobs/pipecatapp.nomad
    dest: /opt/nomad/jobs/pipecatapp.nomad
  when: "'controller_nodes' in group_names"

- name: Install Playwright browsers using the virtual environment's python
  ansible.builtin.command:
    cmd: /opt/pipecatapp/venv/bin/python3 -m playwright install
  become: yes
