- name: Create Nomad jobs directory
  ansible.builtin.file:
    path: /opt/nomad/jobs
    state: directory
    mode: '0755'
  become: yes

- name: Copy pipecatapp Nomad job file
  ansible.builtin.template:
    src: ../../jobs/pipecatapp.nomad
    dest: /opt/nomad/jobs/pipecatapp.nomad
  become: yes

- name: Install systemd service for starting Nomad jobs on boot
  ansible.builtin.template:
    src: prima-services.service.j2
    dest: /etc/systemd/system/prima-services.service
    mode: '0644'
  become: yes
  notify:
    - Reload systemd
    - Enable and start prima-services

- name: Wait for Nomad API to be ready
  ansible.builtin.uri:
    url: http://127.0.0.1:4646/v1/status/leader
    method: GET
    status_code: 200
  register: nomad_api_status
  until: nomad_api_status.status == 200
  retries: 12 # Total wait time = retries * delay = 60 seconds
  delay: 5   # Wait 5 seconds between retries
  become: yes

- name: Check if pipecat-app job is running
  ansible.builtin.command:
    cmd: nomad job status pipecat-app
  register: pipecat_job_status
  changed_when: false
  ignore_errors: true
  become: yes

- name: Run pipecat-app job
  ansible.builtin.command:
    cmd: nomad job run /opt/nomad/jobs/pipecatapp.nomad
  when: pipecat_job_status.rc != 0
  become: yes

- name: Flush handlers to ensure service is enabled and started
  ansible.builtin.meta: flush_handlers
  become: yes