- name: Install python3, pip, and venv system packages
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
      - python3-venv
    state: present
  become: yes

- name: Install system dependencies for Python packages
  ansible.builtin.apt:
    name:
      # General build tools
      - build-essential
      - python3-dev
      # For tokenizers (from transformers)
      - rustc
      - cargo
      # For PyAudio (from RealtimeSTT)
      - portaudio19-dev
      # For fugashi/MeloTTS
      - mecab
      - libmecab-dev
      - mecab-ipadic-utf8

    state: present
  become: yes

- name: Create a virtual environment for the pipecat app
  ansible.builtin.command:
    cmd: python3 -m venv /home/user/pipecatapp_venv
    creates: /home/user/pipecatapp_venv/bin/pip
  become: no

- name: Create a persistent temporary directory for pip builds
  ansible.builtin.file:
    path: /var/tmp/ansible_pip_build
    state: directory
    mode: '0777'
  become: yes

- name: Copy requirements.txt to remote host
  ansible.builtin.copy:
    src: requirements.txt
    dest: /home/user/requirements.txt

- name: Install/Upgrade base python packages in venv
  ansible.builtin.pip:
    name:
      - pip
      - setuptools
      - wheel
      - cython
    state: latest
    executable: /home/user/pipecatapp_venv/bin/pip3

- name: Install python dependencies with a custom temp directory
  block:
    - name: Install python dependencies into the virtual environment
      ansible.builtin.pip:
        requirements: /home/user/requirements.txt
        executable: /home/user/pipecatapp_venv/bin/pip3
  environment:
    TMPDIR: /var/tmp/ansible_pip_build

- name: Copy pipecat app
  ansible.builtin.copy:
    src: app.py
    dest: /home/user/app.py

- name: Copy pipecatapp Nomad job file
  ansible.builtin.template:
    src: ../../jobs/pipecatapp.nomad
    dest: /home/user/pipecatapp.nomad
  when: "'controller_nodes' in group_names"

- name: Install Playwright browsers using the virtual environment's python
  ansible.builtin.command:
    cmd: /home/user/pipecatapp_venv/bin/python3 -m playwright install
  become: no
