- name: Install python3, pip, and venv
  apt:
    name:
      - python3
      - python3-pip
      - python3-venv #<-- Make sure venv is installed
    state: present

- name: Create a virtual environment for the application
  command:
    cmd: python3 -m venv /home/user/pipecat_venv
    creates: /home/user/pipecat_venv/bin/pip #<-- This makes the task idempotent

- name: Copy requirements.txt
  copy:
    src: requirements.txt
    dest: /home/user/requirements.txt

- name: Install python dependencies into the virtual environment
  pip:
    requirements: /home/user/requirements.txt
    # This is the key: point to the pip inside your venv
    executable: /home/user/pipecat_venv/bin/pip3

- name: Copy pipecat app
  copy:
    src: app.py
    dest: /home/user/app.py

- name: Copy pipecat Nomad job file
  template:
    src: ../../jobs/pipecatapp.nomad
    dest: /home/user/pipecatapp.nomad
  when: "'controller_nodes' in group_names"

- name: Install Playwright browsers using the virtual environment's python
  command:
    # Use the python from the venv to run the command
    cmd: /home/user/pipecat_venv/bin/python3 -m playwright install
  become: yes
  become_user: "{{ ansible_user }}"
