---
- name: Install libsdl2-dev
  apt:
    name: libsdl2-dev
    state: present

- name: Clone whisper.cpp repository
  git:
    repo: 'https://github.com/ggml-org/whisper.cpp.git'
    dest: /home/user/whisper.cpp
    version: master
    update: yes
    force: yes

- name: Download whisper.cpp model
  command: bash ./models/download-ggml-model.sh base.en
  args:
    chdir: /home/user/whisper.cpp
    creates: /home/user/whisper.cpp/models/ggml-base.en.bin

- name: Configure whisper.cpp build
  command: cmake -B build
  args:
    chdir: /home/user/whisper.cpp

- name: Build whisper.cpp
  command: cmake --build build --config Release -j
  args:
    chdir: /home/user/whisper.cpp
