---
- name: Set default cert dir if not defined
  ansible.builtin.set_fact:
    nomad_temp_cert_dir: "/tmp/nomad_certs"
  when: nomad_temp_cert_dir is not defined

- name: Check if CA certificate exists locally
  ansible.builtin.stat:
    path: "{{ nomad_temp_cert_dir }}/ca.pem"
  register: ca_cert_stat
  delegate_to: localhost
  check_mode: false
  ignore_errors: true

- name: Generate MQTT client keys for nodes
  become: false
  ansible.builtin.command: "openssl genrsa -out {{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.key 2048"
  args:
    creates: "{{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.key"
  delegate_to: localhost
  when: ca_cert_stat.stat.exists

- name: Generate MQTT client CSRs for nodes
  become: false
  ansible.builtin.command: "openssl req -new -key {{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.key -out {{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.csr -subj \"/CN={{ inventory_hostname }}_mqtt_client\""
  args:
    creates: "{{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.csr"
  delegate_to: localhost
  when: ca_cert_stat.stat.exists

- name: Sign MQTT client certificates for nodes
  become: false
  ansible.builtin.command: "openssl x509 -req -in {{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.csr -CA {{ nomad_temp_cert_dir }}/ca.pem -CAkey {{ nomad_temp_cert_dir }}/ca.key -CAcreateserial -out {{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.pem -days 365"
  args:
    creates: "{{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.pem"
  delegate_to: localhost
  when: ca_cert_stat.stat.exists

- name: Copy MQTT client certificate to each node
  ansible.builtin.copy:
    src: "{{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.pem"
    dest: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/mqtt_client.cert.pem"
    mode: '0644'
    owner: nomad
    group: nomad
    remote_src: no
  become: yes
  when: ca_cert_stat.stat.exists

- name: Copy MQTT client key to each node
  ansible.builtin.copy:
    src: "{{ nomad_temp_cert_dir }}/{{ inventory_hostname }}_mqtt_client.key"
    dest: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/mqtt_client.key.pem"
    mode: '0600'
    owner: nomad
    group: nomad
    remote_src: no
  become: yes
  when: ca_cert_stat.stat.exists
