import hmac
import hashlib
import json
import secrets
from typing import Any, Dict

class ToolExecutionSigner:
    """
    Cryptographically signs and verifies tool execution traces using HMAC-SHA256.
    Ensures that tool outputs are generated by the designated runtime enclave
    and not hallucinated.
    """
    def __init__(self, secret_key: bytes = None):
        # Generate a dynamic key for the runtime if not provided
        self._secret_key = secret_key or secrets.token_bytes(32)

    def _normalize_payload(self, tool_name: str, args: Dict[str, Any], result: str) -> bytes:
        """Normalizes the payload to a consistent byte string for signing."""
        payload = {
            "tool": tool_name,
            "args": args,
            "result": result
        }
        # Sort keys to ensure deterministic JSON serialization
        return json.dumps(payload, sort_keys=True).encode('utf-8')

    def sign(self, tool_name: str, args: Dict[str, Any], result: str) -> str:
        """
        Signs the tool execution trace.
        :param tool_name: Name of the executed tool.
        :param args: Arguments passed to the tool.
        :param result: Stringified result of the tool execution.
        :return: A hex string representation of the HMAC signature.
        """
        normalized = self._normalize_payload(tool_name, args, result)
        signature = hmac.new(self._secret_key, normalized, hashlib.sha256).hexdigest()
        return signature

    def verify(self, tool_name: str, args: Dict[str, Any], result: str, signature: str) -> bool:
        """
        Verifies a previously generated signature.
        """
        expected_signature = self.sign(tool_name, args, result)
        # Use hmac.compare_digest to prevent timing attacks
        return hmac.compare_digest(expected_signature, signature)
