#!/bin/bash

echo "This script will create GitHub issues for all incomplete tasks in TODO.md"
echo "Please ensure you have the 'gh' CLI tool installed and configured."

gh issue create --title "Improve Parent Selection Algorithm:" --body "Research alternative selection strategies from evolutionary computation (e.g., tournament selection, novelty search).\nAdd a new command-line argument to `evolve.py` to allow the user to choose the selection strategy (e.g., `--selection-method tournament`).\nImplement the new selection logic in the `select_parent_from_archive` function.\n"
gh issue create --title "Web-Based UI for Campaign Analysis:" --body "Create a new script `archive_server.py` using a lightweight web framework like Flask or FastAPI.\nThe server should have an endpoint that reads the entire `archive/` directory and constructs a JSON representation of the evolutionary tree.\nCreate a simple, single-page HTML/JavaScript frontend that fetches this JSON and uses a library (like D3.js or vis.js) to render an interactive evolutionary tree.\nThe UI should allow clicking on a node to display the agent's full details (code, rationale, fitness, parent) in a side panel.\n"
gh issue create --title "Convert all configuration files to templates: Any file that contains a variable should be a Jinja2 template (`.j2`)."
gh issue create --title "Establish a clear variable hierarchy: Use `group_vars/all.yaml` for system-wide defaults and consider `host_vars/<hostname>.yaml` for machine-specific overrides."
gh issue create --title "Create a `Dockerfile` for the `pipecatapp` application."
gh issue create --title "Build and push the image to a registry as part of the development process."
gh issue create --title "Simplify the Nomad job to use the `docker` driver with the pre-built image."
gh issue create --title "Replace ASCII art: Create a more dynamic and expressive animated character or graphic."
gh issue create --title "Re-evaluate Consul Connect Service Mesh: Create a new feature branch to attempt to re-enable `sidecar_service` in the Nomad job files and document the process."
gh issue create --title "Investigate Advanced Power Management: Research and prototype a more advanced version that uses Wake-on-LAN."
gh issue create --title "Expand the Model Collection: Systematically test and add the remaining LiquidAI nano models to `group_vars/models.yaml`."
gh issue create --title "Security Hardening:" --body "**Remove passwordless sudo:** Modify the sudoers file configuration to require a password for the `target_user`.\n**Run services as non-root users:** Audit all services and ensure they are running as dedicated, non-privileged users where possible.\n"
gh issue create --title "Robust Remote Node Recovery: Add mechanism to recover remote nodes even if network stack is completely broken (possibly via serial console or IPMI automation)."
gh issue create --title "Create a new integration test file for home assistant."
gh issue create --title "Add the new test to `e2e-tests.yaml`."
gh issue create --title "Modify `start_services.sh` to include the home assistant job."
gh issue create --title "Investigate <https://github.com/microsoft/agent-lightning> as a possible agent improvement method."
gh issue create --title "Investigate RPC Provider Monitoring: Research how to expose or scrape metrics from `llamacpp-rpc` providers to aggregate backend performance data."
gh issue create --title "Fix Corrupted Model Files:" --body "The following files are 0 bytes and appear to be corrupted:\n`en_US-lessac-medium.onnx`\n`chat.prompt.bin`\n`bob.prompt.bin`\n"
gh issue create --title "Fix Corrupted Binaries:" --body "The following executable files are 0 bytes:\n`distributed-llama-repo/dllama`\n`distributed-llama-repo/dllama-api`\n"
gh issue create --title "Fix Skipped Test:" --body "`tests/unit/test_home_assistant_template.py`: Test is currently skipped and contains a TODO to re-add it without breaking tests.\n"
gh issue create --title "Reconcile Stale Artifacts:" --body "`docker/pipecatapp/app.py` contains code and TODOs (e.g., vision model failover) that are not present in the source `ansible/roles/pipecatapp/files/app.py`. Determine if these changes should be merged or if the artifact should be regenerated.\n"
gh issue create --title "Vision Model Failover: Implement failover or selection logic for vision models (see `ansible/roles/pipecatapp/files/app.py`)."
gh issue create --title "Refactor Vision Role: The `vision` role is currently minimal (only installs `libgl1`) and does not deploy Frigate as implied by the `frigate_port` variable. It needs to be refactored to actually deploy the service."
