- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - group_vars/models.yaml

  # These variables would be passed on the command line with -e
  # e.g., ansible-playbook deploy_expert.yaml -e "job_name=my-expert ..."
  vars:
    job_name: "default-expert"
    service_name: "llama-api-default"
    nomad_namespace: "default"
    model_list: "{{ expert_models['main'] }}"
    worker_count: 1

  tasks:
    - name: "Render the Llama Expert job template with custom variables"
      ansible.builtin.template:
        src: ansible/jobs/expert.nomad.j2
        dest: /tmp/{{ job_name }}.nomad
        mode: '0644'

    - name: "Wait for Nomad API to be ready"
      ansible.builtin.uri:
        url: http://127.0.0.1:4646/v1/status/leader
        method: GET
        status_code: 200
      register: nomad_api_status
      until: "nomad_api_status.status == 200"
      retries: 12
      delay: 5

    - name: "Run the custom Llama Expert job in Nomad"
      ansible.builtin.command:
        cmd: "nomad job run /tmp/{{ job_name }}.nomad"
      register: nomad_run_result
      changed_when: "'Eval ID' in nomad_run_result.stdout"

    - name: "Display Nomad run output"
      ansible.builtin.debug:
        var: nomad_run_result.stdout_lines
