- name: Deploy Pipecat App
  hosts: all
  remote_user: "{{ target_user | default('pipecatapp') }}"
  become: yes

  vars_files:
    - group_vars/models.yaml

  vars:
    target_user: "pipecatapp"

  roles:
    - role: pipecatapp
      tags: [deploy_app]

  tasks:
    - name: Restart pipecat-app service
      ansible.builtin.systemd:
        name: llama-services.service
        state: restarted
      become: yes
