---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:
    - name: Check Nomad job status for home-assistant
      ansible.builtin.command:
        cmd: "nomad job status home-assistant"
      register: job_status
      changed_when: false
      ignore_errors: yes

    - name: Display Nomad job status
      ansible.builtin.debug:
        var: job_status.stdout

    - name: Get Home Assistant allocations from Nomad API
      ansible.builtin.uri:
        url: "http://127.0.0.1:4646/v1/job/home-assistant/allocations"
      register: ha_allocations_response
      when: job_status.rc == 0 and "'No allocations placed' not in job_status.stdout"
      ignore_errors: yes

    - name: Set latest allocation fact
      ansible.builtin.set_fact:
        latest_ha_allocation: "{{ (ha_allocations_response.json | default([]) | sort(attribute='CreateIndex', reverse=true) | first) }}"
      when: ha_allocations_response.status == 200 and ha_allocations_response.json is defined and ha_allocations_response.json | length > 0

    - name: Get logs for latest home-assistant allocation
      ansible.builtin.command:
        cmd: "nomad alloc logs {{ latest_ha_allocation.ID }}"
      register: alloc_logs
      changed_when: false
      when: latest_ha_allocation is defined and latest_ha_allocation.ID is defined

    - name: Display allocation logs
      ansible.builtin.debug:
        var: alloc_logs.stdout
      when: alloc_logs is defined

    - name: Check permissions of ha-config directory
      ansible.builtin.stat:
        path: /opt/nomad/volumes/ha-config
      register: ha_config_stat

    - name: Display permissions of ha-config directory
      ansible.builtin.debug:
        var: ha_config_stat.stat
