- name: Heal Core Services | Ensure core infrastructure is running
  hosts: controller_nodes[0] # This should run on the primary controller
  connection: local
  become: no
  gather_facts: yes

  vars_files:
    - group_vars/all.yaml
    - group_vars/models.yaml

  vars:
    target_user: "loki"

  tasks:
    - name: Ensure llamacpp-rpc job is running
      ansible.builtin.include_role:
        name: bootstrap_agent
        tasks_from: deploy_llama_cpp_model.yaml

    - name: Ensure pipecat-app job is running
      ansible.builtin.include_role:
        name: pipecatapp
        tasks_from: main.yaml