- name: Heal Core Services | Ensure core infrastructure is running
  hosts: controller_nodes[0] # This should run on the primary controller
  connection: local
  become: no

  vars_files:
    - group_vars/all.yaml
    - group_vars/models.yaml

  tasks:
    - name: Ensure prima-expert-main job is running
      ansible.builtin.include_role:
        name: bootstrap_agent
        tasks_from: deploy_llama_cpp_model.yaml

    - name: Ensure pipecat-app job is running
      ansible.builtin.include_role:
        name: pipecatapp
        tasks_from: main.yaml
