[mypy]
ignore_missing_imports = True
exclude = (?x)(
    ^venv/ |
    ^\.venv/ |
    ^node_modules/ |
    ^tests/
  )

[mypy-requests.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-aiofiles.*]
ignore_missing_imports = True
