- name: Test the llama_cpp role
  hosts: all
  remote_user: "{{ target_user }}"
  become: yes

  vars_files:
    - group_vars/all.yaml
    - group_vars/models.yaml

  roles:
    - system_deps
    - common
    - consul
    - docker
    - nomad

  tasks:
    - name: Flush handlers to ensure core services are started
      meta: flush_handlers

    - name: Wait for a Consul leader to be elected
      ansible.builtin.uri:
        url: "http://127.0.0.1:8500/v1/status/leader"
        return_content: yes
      register: consul_leader_status
      until: consul_leader_status.content != '""' and consul_leader_status.status == 200
      retries: 12
      delay: 5
      ignore_errors: yes

    - name: Populate Consul KV with configuration
      include_role:
        name: config_manager
      run_once: true

    - name: Run download_models role
      include_role:
        name: download_models
      when: not external_model_server

    - name: Flush handlers again before running llama_cpp
      meta: flush_handlers

    - name: Run llama_cpp role
      include_role:
        name: llama_cpp
      when: not external_model_server
