# Defaults for the paddler_balancer role

# User and group to run the paddler-balancer service
paddler_balancer_user: "paddler"
paddler_balancer_group: "paddler"

# Working directory for the paddler-balancer service
# This directory will be created if it doesn't exist.
paddler_balancer_working_directory: "/opt/paddler"

# Management interface for agents to connect
paddler_balancer_management_port: 8085
paddler_balancer_management_addr: "0.0.0.0:{{ paddler_balancer_management_port }}"

# Reverse proxy interface for external clients
paddler_balancer_reverseproxy_port: 8080
paddler_balancer_reverseproxy_addr: "0.0.0.0:{{ paddler_balancer_reverseproxy_port }}"

# Enable the web dashboard for the balancer
paddler_balancer_dashboard_enable: true

# StatsD address for metrics (e.g., "127.0.0.1:8125")
# Leave empty to disable StatsD.
paddler_balancer_statsd_addr: ""

# Path to the paddler executable
paddler_executable_path: "/usr/local/bin/paddler"
