#!/bin/bash
#
# Unified Wrapper Script for pipecatapp
#
# This script is generated by Ansible and ensures that the pipecat application
# is run correctly in both raw_exec and Docker environments.

# Exit immediately if a command exits with a non-zero status.
set -e

# Change to the application directory
cd /opt/pipecatapp

# Activate the virtual environment
source /opt/pipecatapp/venv/bin/activate

echo "--- Starting pipecat-app: $(date) ---"

# For Docker, we log to stdout/stderr and let the container runtime handle it.
exec /opt/pipecatapp/venv/bin/python3 /opt/pipecatapp/app.py
