---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      ansible.builtin.raw: apt-get update -y
      register: result
      changed_when: "result.rc == 0"
      failed_when: "result.rc != 0"
    - name: Install python3, sudo, and ca-certificates
      ansible.builtin.raw: apt-get install -y python3 sudo ca-certificates
      register: result
      changed_when: "result.rc == 0 and 'is already installed' not in result.stdout"
      failed_when: "result.rc != 0 and 'Unable to locate package' in result.stderr"
