- name: run nomad llamacpp-rpc job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run -detach "/tmp/rpc-{{ item.filename | regex_replace('[^a-zA-Z0-9-]', '-') }}.nomad"
  loop: "{{ all_models_for_rpc }}"
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip | default('127.0.0.1') }}:{{ nomad_http_port | default(4646) }}"
    NOMAD_CACERT: "/etc/nomad.d/tls/ca.pem"
    NOMAD_CLIENT_CERT: "/etc/nomad.d/tls/cli.cert.pem"
    NOMAD_CLIENT_KEY: "/etc/nomad.d/tls/cli.key.pem"
    NOMAD_TLS_SKIP_VERIFY: "1"
  loop_control:
    label: "{{ item.filename }}"
  become: yes

- name: update ld cache
  ansible.builtin.command:
    cmd: ldconfig
  become: yes
