- name: run nomad llamacpp-rpc job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run -detach "/tmp/rpc-{{ item.filename | regex_replace('[^a-zA-Z0-9-]', '-') }}.nomad"
  loop: "{{ all_models_for_rpc }}"
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip | default('127.0.0.1') }}:{{ nomad_http_port | default(4646) }}"
    NOMAD_CACERT: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/ca.pem"
    NOMAD_CLIENT_CERT: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/cert.pem"
    NOMAD_CLIENT_KEY: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/key.pem"
    NOMAD_TLS_SKIP_VERIFY: "1"
  loop_control:
    label: "{{ item.filename }}"
  become: yes

- name: update ld cache
  ansible.builtin.command:
    cmd: ldconfig
  become: yes
