- name: Create Traefik directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  become: yes
  loop:
    - "{{ nomad_jobs_dir }}"

- name: Template Traefik Nomad job
  ansible.builtin.template:
    src: traefik.nomad.j2
    dest: "{{ nomad_jobs_dir }}/traefik.nomad"
  become: yes

- name: Run Traefik Nomad job
  ansible.builtin.command: nomad job run -detach {{ nomad_jobs_dir }}/traefik.nomad
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip | default('127.0.0.1') }}:{{ nomad_http_port | default(4646) }}"
    NOMAD_CACERT: "/etc/nomad.d/tls/ca.pem"
    NOMAD_CLIENT_CERT: "/etc/nomad.d/tls/cert.pem"
    NOMAD_CLIENT_KEY: "/etc/nomad.d/tls/key.pem"
  register: traefik_deploy
  changed_when: "'modified' in traefik_deploy.stdout or 'created' in traefik_deploy.stdout"
  become: yes
