- name: Install desktop extras packages
  ansible.builtin.apt:
    name:
      - lolcat
      - figlet
      - hollywood
      - sl
      - fortune
      - cowsay
      - toilet
      - cmatrix
      - make
    state: present
  become: yes

- name: Clone figlet-fonts repository
  ansible.builtin.git:
    repo: 'https://github.com/xero/figlet-fonts.git'
    dest: /home/user/.local/share/fonts
    version: master
    update: yes

- name: Create a temporary build directory for no-more-secrets
  ansible.builtin.tempfile:
    state: directory
    suffix: nms-build
  register: nms_build_dir

- name: Clone no-more-secrets repository
  ansible.builtin.git:
    repo: 'https://github.com/bartobri/no-more-secrets.git'
    dest: "{{ nms_build_dir.path }}"
    version: master
    update: yes

- name: Build no-more-secrets
  ansible.builtin.command:
    cmd: make nms
  args:
    chdir: "{{ nms_build_dir.path }}"
    creates: "{{ nms_build_dir.path }}/nms"

- name: Install no-more-secrets
  ansible.builtin.command:
    cmd: make install
  args:
    chdir: "{{ nms_build_dir.path }}"
    creates: /usr/local/bin/nms
  become: yes

- name: Clean up no-more-secrets build directory
  ansible.builtin.file:
    path: "{{ nms_build_dir.path }}"
    state: absent
  when: nms_build_dir.path is defined
