---
- name: Render peer-gateway job template
  template:
    src: peer-gateway.nomad.j2
    dest: /opt/nomad/jobs/peer-gateway.nomad
    mode: '0644'

- name: Run peer-gateway job
  command: nomad job run /opt/nomad/jobs/peer-gateway.nomad
  environment:
    NOMAD_ADDR: "http://127.0.0.1:4646"
  register: nomad_run
  changed_when: "'Job registration successful' in nomad_run.stdout"
  ignore_errors: yes
