# This role is deprecated and will be replaced by a Piper TTS implementation.
# The Python dependencies for the original KittenTTS have been merged into the
# central requirements.txt file in the 'python_deps' role.
# This role is now intentionally left empty.
