import importlib

__all__ = [
    "DatalogExtractionTool",
    "ShuntTool",
    "Ansible_Tool",
    "ArchivistTool",
    "ASTEditorTool",
    "ATProtoTool",
    "AutoloopTool",
    "AutoresearchTool",
    "ClusterStatusTool",
    "CodeRunnerTool",
    "ContainerRegistryTool",
    "ContextUploadTool",
    "CouncilTool",
    "CQ_Tool",
    "DependencyScannerTool",
    "DesktopControlTool",
    "DocumentTool",
    "DynamicSkillTool",
    "ExperimentTool",
    "ExternalAppManagerTool",
    "FileEditorTool",
    "FinalAnswerTool",
    "GetNomadJobTool",
    "GitCoordinationTool",
    "Git_Tool",
    "HA_Tool",
    "HereticTool",
    "JacobianLensTool",
    "JulesTool",
    "Last30DaysTool",
    "LangChainToolAdapter",
    "LightweightProjectMapperTool",
    "LLxprt_Code_Tool",
    "MCPClientAdapter",
    "MCP_Tool",
    "MTACTool",
    "OCRTool",
    "OpenWorkersTool",
    "OpenClawTool",
    "OpenCodeProviderTool",
    "OpencodeTool",
    "OrchestratorTool",
    "OuroborosTool",
    "P2PSyncTool",
    "PersonalityTool",
    "PlannerTool",
    "PolyphonyTool",
    "Power_Tool",
    "ProjectMapperTool",
    "ProjectOverviewTool",
    "PromptImproverTool",
    "RAG_Tool",
    "SaveSkillTool",
    "ScaleComputeTool",
    "SchedulerTool",
    "SchemaHarnessTool",
    "SchemaMapperTool",
    "SearchSkillsTool",
    "SearchTool",
    "SetOperationalModeTool",
    "ShellTool",
    "SkillBuilderTool",
    "SmolAgentTool",
    "SpecLoaderTool",
    "SSH_Tool",
    "SubmitSolutionTool",
    "SummarizerTool",
    "SwarmTool",
    "TermEverythingTool",
    "TernlightTool",
    "UpdateLitellmTool",
    "SSDStreamingTool",
    "UnitReasoningTool",
    "VRTool",
    "WasmTool",
    "WebBrowserTool",
    "WOLTool",
    "HolographicMemoryTool",
    "WorkspaceTool",
    "SubstrateVisualizerTool",
]

_module_lookup = {
    "DatalogExtractionTool": "datalog_extraction_tool",
    "ShuntTool": "shunt_tool",
    "Ansible_Tool": "ansible_tool",
    "ArchivistTool": "archivist_tool",
    "ASTEditorTool": "ast_editor_tool",
    "ATProtoTool": "atproto_tool",
    "AutoloopTool": "autoloop_tool",
    "AutoresearchTool": "autoresearch_tool",
    "ClusterStatusTool": "cluster_status_tool",
    "CodeRunnerTool": "code_runner_tool",
    "ContainerRegistryTool": "container_registry_tool",
    "ContextUploadTool": "context_upload_tool",
    "CouncilTool": "council_tool",
    "CQ_Tool": "cq_tool",
    "DependencyScannerTool": "dependency_scanner_tool",
    "DesktopControlTool": "desktop_control_tool",
    "DocumentTool": "document_tool",
    "DynamicSkillTool": "dynamic_skill_tool",
    "ExperimentTool": "experiment_tool",
    "ExternalAppManagerTool": "external_app_manager_tool",
    "FileEditorTool": "file_editor_tool",
    "FinalAnswerTool": "final_answer_tool",
    "GetNomadJobTool": "get_nomad_job",
    "GitCoordinationTool": "git_coordination_tool",
    "Git_Tool": "git_tool",
    "HA_Tool": "ha_tool",
    "HereticTool": "heretic_tool",
    "JacobianLensTool": "jacobian_lens_tool",
    "JulesTool": "jules_tool",
    "Last30DaysTool": "last30days_tool",
    "LangChainToolAdapter": "langchain_adapter_tool",
    "LightweightProjectMapperTool": "lightweight_project_mapper_tool",
    "LLxprt_Code_Tool": "llxprt_code_tool",
    "MCPClientAdapter": "mcp_client_adapter",
    "MCP_Tool": "mcp_tool",
    "MTACTool": "mtac_tool",
    "OCRTool": "ocr_tool",
    "OpenWorkersTool": "open_workers_tool",
    "OpenClawTool": "openclaw_tool",
    "OpenCodeProviderTool": "opencode_provider_tool",
    "OpencodeTool": "opencode_tool",
    "OrchestratorTool": "orchestrator_tool",
    "OuroborosTool": "ouroboros_tool",
    "P2PSyncTool": "p2p_sync_tool",
    "PersonalityTool": "personality_tool",
    "PlannerTool": "planner_tool",
    "PolyphonyTool": "polyphony_tool",
    "Power_Tool": "power_tool",
    "ProjectMapperTool": "project_mapper_tool",
    "ProjectOverviewTool": "project_overview_tool",
    "PromptImproverTool": "prompt_improver_tool",
    "RAG_Tool": "rag_tool",
    "SaveSkillTool": "save_skill_tool",
    "ScaleComputeTool": "scale_compute_tool",
    "SchedulerTool": "scheduler_tool",
    "SchemaHarnessTool": "schema_harness_tool",
    "SchemaMapperTool": "schema_mapper_tool",
    "SearchSkillsTool": "search_skills_tool",
    "SearchTool": "search_tool",
    "SetOperationalModeTool": "set_operational_mode_tool",
    "ShellTool": "shell_tool",
    "SkillBuilderTool": "skill_builder_tool",
    "SmolAgentTool": "smol_agent_tool",
    "SpecLoaderTool": "spec_loader_tool",
    "SSH_Tool": "ssh_tool",
    "SubmitSolutionTool": "submit_solution_tool",
    "SummarizerTool": "summarizer_tool",
    "SwarmTool": "swarm_tool",
    "TermEverythingTool": "term_everything_tool",
    "TernlightTool": "ternlight_tool",
    "UpdateLitellmTool": "update_litellm_tool",
    "SSDStreamingTool": "ssd_streaming_tool",
    "UnitReasoningTool": "unit_reasoning_tool",
    "VRTool": "vr_tool",
    "WasmTool": "wasm_tool",
    "WebBrowserTool": "web_browser_tool",
    "WOLTool": "wol_tool",
    "HolographicMemoryTool": "holographic_memory_tool",
    "WorkspaceTool": "workspace_tool",
    "SubstrateVisualizerTool": "substrate_visualizer_tool",
}

def __getattr__(name):
    if name in _module_lookup:
        module_name = _module_lookup[name]
        module = importlib.import_module(f".{module_name}", package=__name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
