- name: "Run nomad job"
  ansible.builtin.command:
    cmd: "nomad job run /opt/nomad/jobs/world_model.nomad"
  environment:
    NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
  changed_when: true
  become: no
  async: 300
  poll: 0
