- name: Run Forgejo Job
  ansible.builtin.command: nomad job run -detach /opt/nomad/jobs/forgejo.nomad
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip | default('127.0.0.1') }}:{{ nomad_http_port | default(4646) }}"
    NOMAD_CACERT: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/ca.pem"
    NOMAD_CLIENT_CERT: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/cert.pem"
    NOMAD_CLIENT_KEY: "{{ nomad_tls_dir | default('/etc/nomad.d/tls') }}/key.pem"
    NOMAD_TLS_SKIP_VERIFY: "1"
  become: yes