- name: Run Forgejo Job
  ansible.builtin.command: nomad job run -detach /opt/nomad/jobs/forgejo.nomad
  become: yes
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip }}:{{ nomad_http_port | default(4646) }}"
