- name: Create Paperless directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
  loop:
    - /opt/paperless/data
    - /opt/paperless/media
    - /opt/paperless/export
    - /opt/paperless/consume
    - /opt/paperless/postgres
    - /opt/paperless/redis
  become: yes

- name: Create Paperless DB Nomad job file
  ansible.builtin.template:
    src: paperless-db.nomad.j2
    dest: /opt/nomad/jobs/paperless-db.nomad
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Run Paperless DB Job

- name: Create Paperless Redis Nomad job file
  ansible.builtin.template:
    src: paperless-redis.nomad.j2
    dest: /opt/nomad/jobs/paperless-redis.nomad
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Run Paperless Redis Job

- name: Create Paperless App Nomad job file
  ansible.builtin.template:
    src: paperless-app.nomad.j2
    dest: /opt/nomad/jobs/paperless-app.nomad
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Run Paperless App Job
