- name: Install prima.cpp dependencies
  ansible.builtin.apt:
    name:
      - fio
      - libzmq3-dev
      - g++
      - highs
      - cmake
      - git
      - build-essential
    state: present
  become: yes

- name: Create build directory for prima.cpp
  ansible.builtin.file:
    path: "{{ primacpp_install_dir }}"
    state: directory
    mode: '0755'
  become: yes

- name: Clone prima.cpp repository
  ansible.builtin.git:
    repo: "{{ primacpp_git_repo }}"
    dest: "{{ primacpp_install_dir }}"
    version: master
    update: yes
  become: yes
  register: primacpp_git_result

- name: Build and install from source if updated
  block:
    - name: Configure prima.cpp build
      ansible.builtin.command:
        cmd: cmake -B build
      args:
        chdir: "{{ primacpp_install_dir }}"
        creates: "{{ primacpp_install_dir }}/build/Makefile"
      when: "'worker_nodes' in group_names and 'controller_nodes' not in group_names"

    - name: Configure prima.cpp build with HiGHS
      ansible.builtin.command:
        cmd: cmake -B build -DUSE_HIGHS=1
      args:
        chdir: "{{ primacpp_install_dir }}"
        creates: "{{ primacpp_install_dir }}/build/Makefile"
      when: "'controller_nodes' in group_names"

    - name: Build prima.cpp
      ansible.builtin.command:
        cmd: cmake --build build --config Release -j
      args:
        chdir: "{{ primacpp_install_dir }}"
        creates: "{{ primacpp_install_dir }}/build/bin/primaserver" # Assuming 'primaserver' is a binary

    - name: Find compiled binaries
      ansible.builtin.find:
        paths: "{{ primacpp_install_dir }}/build/bin"
        patterns: '*'
        file_type: file
      register: primacpp_binaries

    - name: Install prima.cpp binaries
      ansible.builtin.copy:
        src: "{{ item.path }}"
        dest: "/usr/local/bin/{{ item.path | basename }}"
        mode: '0755'
        remote_src: yes
      loop: "{{ primacpp_binaries.files }}"

    - name: Clean up prima.cpp build directory
      ansible.builtin.file:
        path: "{{ primacpp_install_dir }}"
        state: absent
  when: primacpp_git_result.changed
  become: yes

- name: Template the prima-expert-main Nomad job file
  ansible.builtin.template:
    src: prima-expert.nomad.j2
    dest: /opt/nomad/jobs/prima-expert.nomad
  vars:
    model_path: "/opt/nomad/models/llm/Llama-3-8B-Instruct-GGUF/Llama-3-8B-Instruct-Q4_K_M.gguf"
  when: "'controller_nodes' in group_names"

- name: Check if prima-expert-main job is running
  ansible.builtin.command:
    cmd: nomad job status prima-expert-main
  register: primacpp_job_status
  changed_when: false
  failed_when: false # Don't fail if the job doesn't exist
  environment:
    NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"

- name: Run prima-expert-main job
  ansible.builtin.command:
    cmd: nomad job run /opt/nomad/jobs/prima-expert.nomad
  when: primacpp_job_status.rc != 0
  environment:
    NOMAD_ADDR: "http://{{ ansible_default_ipv4.address }}:4646"
