- name: Restart Home Assistant
  ansible.builtin.command:
    cmd: nomad job run -detach {{ nomad_jobs_dir }}/home-assistant.nomad
  environment:
    NOMAD_ADDR: "https://{{ cluster_ip | default('127.0.0.1') }}:{{ nomad_http_port | default(4646) }}"
        NOMAD_CACERT: "/etc/nomad.d/tls/ca.pem"
        NOMAD_CLIENT_CERT: "/etc/nomad.d/tls/cert.pem"
        NOMAD_CLIENT_KEY: "/etc/nomad.d/tls/key.pem"
  changed_when: true
