- name: Restart Vision Job
  ansible.builtin.command:
    cmd: /usr/local/bin/nomad job run -detach {{ nomad_jobs_dir }}/vision.nomad
  environment:
    NOMAD_ADDR: "http://{{ cluster_ip }}:{{ nomad_http_port | default(4646) }}"
  changed_when: true
