- name: Force kill stuck nomad processes
  ansible.builtin.shell: "pkill -9 nomad || true"
  ignore_errors: false
  become: yes
  when: not ansible_check_mode

- name: Restart nomad service
  ansible.builtin.service:
    name: nomad
    state: restarted
    enabled: true
    daemon_reload: true
  when: not ansible_check_mode
