#!/bin/bash

# This script dynamically generates the Ansible inventory.yaml file
# by querying the Consul API for the current list of cluster members.

set -e

# Determine the project root directory to locate the inventory.yaml file
# This makes the script runnable from any location.
REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
INVENTORY_FILE="$REPO_ROOT/inventory.yaml"

log() {
    echo "[InventoryGen] $1"
}

log "Starting dynamic inventory generation..."

# Wait for Consul to be available
for i in {1..24}; do
    if curl -s "http://127.0.0.1:8500/v1/status/leader" &> /dev/null; then
        log "Consul agent is available."
        break
    fi
    log "Waiting for Consul..."
    sleep 5
done

CONSUL_TOKEN="${CONSUL_HTTP_TOKEN:-}"
if [ -z "$CONSUL_TOKEN" ] && [ -f "/etc/consul.d/consul.env" ]; then
    CONSUL_TOKEN=$(grep -oP 'CONSUL_HTTP_TOKEN=\K\S+' /etc/consul.d/consul.env 2>/dev/null || true)
fi
if [ -z "$CONSUL_TOKEN" ] && [ -f "$REPO_ROOT/group_vars/all.yaml" ]; then
    CONSUL_TOKEN=$(grep -oP 'consul_bootstrap_token:\s*"\K[^"]+' "$REPO_ROOT/group_vars/all.yaml" 2>/dev/null || true)
fi

TOKEN_HEADER=()
if [ -n "$CONSUL_TOKEN" ]; then
    TOKEN_HEADER=(-H "X-Consul-Token: $CONSUL_TOKEN")
fi

# Fetch all nodes from the Consul catalog. These are the workers.
ALL_NODES=$(curl -s "${TOKEN_HEADER[@]}" http://127.0.0.1:8500/v1/catalog/nodes | jq -r '.[] | .Address' 2>/dev/null | sort -u)
if [ -z "$ALL_NODES" ]; then
    log "Could not fetch nodes from Consul. Aborting."
    exit 1
fi

# Fetch the nodes running the 'nomad' service. These are the controllers.
CONTROLLER_NODES=$(curl -s "${TOKEN_HEADER[@]}" http://127.0.0.1:8500/v1/catalog/service/nomad | jq -r '.[].Address' 2>/dev/null | sort -u)
if [ -z "$CONTROLLER_NODES" ]; then
    log "Could not fetch controller nodes (nomad service) from Consul. Using all nodes as workers only."
fi

log "Generating inventory file at $INVENTORY_FILE"

# Start with a clean inventory file
> "$INVENTORY_FILE"

# Write the structure to the YAML file
cat > "$INVENTORY_FILE" << EOF
# This inventory is dynamically generated by update_inventory.sh
all:
  children:
    worker_nodes:
      hosts:
EOF

for node in $ALL_NODES; do
  echo "        $node:" >> "$INVENTORY_FILE"
done

# Only add the controller_nodes group if any were found
if [ -n "$CONTROLLER_NODES" ]; then
cat >> "$INVENTORY_FILE" << EOF
    controller_nodes:
      hosts:
EOF

for node in $CONTROLLER_NODES; do
  echo "        $node:" >> "$INVENTORY_FILE"
done
fi

log "Inventory file generated successfully with $(echo "$ALL_NODES" | wc -w) worker(s) and $(echo "$CONTROLLER_NODES" | wc -w) controller(s)."
