- name: Create Forgejo data directory
  ansible.builtin.file:
    path: /opt/forgejo/data
    state: directory
    mode: '0755'
    owner: "1000"
    group: "1000"
  become: yes

- name: Create Forgejo config directory
  ansible.builtin.file:
    path: /opt/forgejo/config
    state: directory
    mode: '0755'
    owner: "1000"
    group: "1000"
  become: yes

- name: Create Forgejo Nomad job file
  ansible.builtin.template:
    src: forgejo.nomad.j2
    dest: /opt/nomad/jobs/forgejo.nomad
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: Run Forgejo Job
