- name: Install Tailscale
  shell: curl -fsSL https://tailscale.com/install.sh | sh
  args:
    creates: /usr/bin/tailscale

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

- name: Ensure tailscaled is started and enabled
  ansible.builtin.systemd:
    name: tailscaled
    state: started
    enabled: yes

- name: Check Tailscale status
  command: tailscale status
  register: tailscale_status
  failed_when: false
  changed_when: false


- name: Check for imprinted Headscale URL
  ansible.builtin.stat:
    path: /etc/pipecat_headscale_url
  register: imprinted_headscale_url_file

- name: Check for imprinted Headscale Auth Key
  ansible.builtin.stat:
    path: /etc/pipecat_mesh_auth_key
  register: imprinted_headscale_auth_key_file

- name: Read imprinted Headscale URL
  ansible.builtin.command: cat /etc/pipecat_headscale_url
  register: imprinted_headscale_url
  when: imprinted_headscale_url_file.stat.exists
  changed_when: false

- name: Read imprinted Headscale Auth Key
  ansible.builtin.command: cat /etc/pipecat_mesh_auth_key
  register: imprinted_headscale_auth_key
  when: imprinted_headscale_auth_key_file.stat.exists
  changed_when: false

- name: Set dynamic Tailscale login-server
  set_fact:
    resolved_login_server: "{{ imprinted_headscale_url.stdout if imprinted_headscale_url_file.stat.exists else hostvars[groups['controller_nodes'][0]]['headscale_server_url'] }}"

- name: Generate single-use Headscale auth key for this node
  ansible.builtin.command: /usr/local/bin/headscale --user {{ headscale_namespace | default('default') }} preauthkeys create --expiration 10m
  delegate_to: "{{ groups['controller_nodes'][0] }}"
  register: dynamic_headscale_auth_key_output
  changed_when: true
  when: >
    tailscale_status.rc != 0 and
    not imprinted_headscale_auth_key_file.stat.exists

- name: Set dynamic Tailscale authkey
  set_fact:
    resolved_authkey: >-
      {%- if imprinted_headscale_auth_key_file.stat.exists -%}
      {{ imprinted_headscale_auth_key.stdout }}
      {%- else -%}
      {{ dynamic_headscale_auth_key_output.stdout_lines[-1] }}
      {%- endif -%}
  when: tailscale_status.rc != 0

- name: Connect to Headscale
  command: >
    tailscale up
    --login-server={{ resolved_login_server }}
    --authkey={{ resolved_authkey }}
    --accept-routes
  when: tailscale_status.rc != 0
  register: tailscale_up
  changed_when: "'Success' in tailscale_up.stdout"

- name: Wait for tailscale0 interface to have an IP
  ansible.builtin.shell: 'tailscale ip -4 | grep "^100\."'
  args:
    executable: /bin/bash
  register: tailscale_ip_check
  until: tailscale_ip_check.rc == 0
  retries: 24
  delay: 5
  changed_when: false

- name: Refresh network facts
  setup:
    gather_subset:
      - network
