---
# tasks file for docker

- name: Create the Docker configuration directory
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'
  become: true

- name: Place the Docker daemon configuration file
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  become: true
  notify: Restart Docker

- name: Download the get-docker.sh script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: '0755'

- name: Run the Docker installation script
  ansible.builtin.shell:
    cmd: /tmp/get-docker.sh
    creates: /usr/bin/docker
  become: true

- name: Add user to the 'docker' group for rootless execution
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true

- name: Ensure Docker service is started and enabled
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes
  become: true
