- name: Home Assistant Integration Test
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for Home Assistant to be ready
      ansible.builtin.uri:
        url: "http://127.0.0.1:8123"
        status_code: 200
      register: ha_status
      until: ha_status.status == 200
      retries: 20
      delay: 15
      ignore_errors: yes

    - name: Fail if Home Assistant is not running
      ansible.builtin.fail:
        msg: "Home Assistant is not running or not responding on port 8123."
      when: ha_status.status != 200