- name: Common Setup
  hosts: all
  become: yes
  roles:
    - role: tpm_ssh
      tags:
        - tpm_ssh
        - common

  tasks:
    - name: Ensure Debian repositories are configured (needed for minimal/live ISOs)
      raw: |
        cat <<EOF > /etc/apt/sources.list
        deb http://deb.debian.org/debian trixie main contrib non-free-firmware
        deb http://security.debian.org/debian-security trixie-security main contrib non-free-firmware
        deb http://deb.debian.org/debian trixie-updates main contrib non-free-firmware
        EOF
      changed_when: false

    - name: Import missing Debian GPG keys
      raw: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6ED0E7B82643E131 78DBA3BC47EF2265 762F67A0B2C39DE4 BDE6D2B9216EC7A8 8E9F831205B4BA95
      changed_when: false

    - name: Run apt-get update to ensure cache is populated before any modules run
      raw: apt-get update
      changed_when: false

    - name: Ensure the sudo package is installed
      tags:
        - sudo
      ansible.builtin.apt:
        name: sudo
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: Ensure the rsync package is installed
      tags:
        - rsync
      ansible.builtin.apt:
        name: rsync
        state: present

    - name: Ensure the sudo group exists
      tags:
        - sudo
      ansible.builtin.group:
        name: sudo
        state: present

    - name: Create the '{{ target_user }}' account with sudo access
      tags:
        - user
      ansible.builtin.user:
        name: "{{ target_user }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Set correct permissions for the user's home directory
      tags:
        - user
      ansible.builtin.file:
        path: "/home/{{ target_user }}"
        state: directory
        mode: '0755'
