echo ""
echo "================================================================"
echo " Welcome to the Pipecat Cluster Installer!                      "
echo "================================================================"
echo ""
echo " The system is running from the bootable media."
echo " To install and configure the cluster agent or control node, run:"
echo ""
echo "   cd /opt/pipecat-cluster && sudo ./bootstrap.sh"
echo ""
echo " For more details, see the README.md in the project directory."
echo "================================================================"
echo ""
